services:
  - type: web
    name: house-of-varsh-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: RAZORPAY_KEY_ID
        value: rzp_live_TRD6mlUZHguUAm
      - key: RAZORPAY_KEY_SECRET
        value: Oh6FXaAJdnOHNQhE4yNJAxEa

